export const AppRoute = {
  // AUTH: 'Auth',
  LOGIN: 'LoginPage',
  HOME: 'HomePage',
  AUTHENTICATION: 'AuthenticationPage',
  FEATURE: 'FeaturePage',
  MY: 'MyPage',
  PERSONALINFO: 'PersonalInfo',
  IDCARDVERTIFY: 'IdCardVertifyPage',
  PASSPORTVERTIFY: 'PassportVertifyPage',
  VERDETAILS: 'VertifyDetailsPage',
  UNRECORD: 'UnrecordedHouse',
  RECORD: 'RecordHouse',
  AUDIT: 'AuditHouse',
  HOUSEDETAIL: 'HouseDetail',
  PUBLICHOUSEDETAIL: 'PublicHouseDetail',
  PUBLISH: 'PublishHouse',
  ADDTENANT: 'AddTenant',
  HOUSELIST: 'HouseList',
  COMPONENTTEST: 'ComponentTest',
  ROOM: 'RoomPage',
  MYHOUSELIST: 'MyHouseList',
  MAPHOUSE: 'MapHouse',
  PUBLISHLISE: 'MyPublishHouse',
};
Object.freeze(AppRoute);
