const vertifyCn = [
  {
    name: '真实姓名',
    placeholder: '请输入真实姓名',
    key: 'name',
    type: 'INPUT',
    required: true,
    errorMsg: ['请输入真实姓名'],
  },
  {
    name: '身份证号',
    placeholder: '请输入身份证号',
    key: 'identificationNo',
    type: 'INPUT',
    required: true,
    errorMsg: ['请输入身份证号'],
  },
  {
    name: '性别',
    placeholder: '请选择性别',
    key: 'gender',
    type: 'RADIO',
    initial: 'male',
    required: true,
    selectOptions: [{label: '男', value: 'male'}, {label: '女', value: 'female'}],
  },
  {
    name: '民族',
    placeholder: '请选择民族',
    key: 'nation',
    required: true,
    type: 'PICKER',  //'INPUT', 
    errorMsg: ['请输入民族'],
    selectOptions: ["汉族", "蒙古族", "回族", "藏族", "维吾尔族", "苗族", "彝族", "壮族", "布依族", "朝鲜族", "满族", "侗族",
    "瑶族", "白族", "土家族", "哈尼族", "哈萨克族", "傣族", "黎族", "傈僳族", "佤族", "畲族", "高山族", "拉祜族", "水族", "东乡族",
    "纳西族", "景颇族", "柯尔克孜族", "土族", "达斡尔族", "仫佬族", "羌族", "布朗族", "撒拉族", "毛难族", "仡佬族", "锡伯族", "阿昌族",
    "普米族", "塔吉克族", "怒族", "乌孜别克族", "俄罗斯族", "鄂温克族", "崩龙族", "保安族", "裕固族", "京族", "塔塔尔族", "独龙族",
    "鄂伦春族", "赫哲族", "门巴族", "珞巴族", "基诺族"],
  },
  {
    name: '出生日期',
    required: true,
    placeholder: '请选择出生日期',
    key: 'birthDate',
    type: 'DATE',
    errorMsg: ['请选择出生日期'],
  },
  {
    name: '身份证地址',
    required: true,
    placeholder: '请输入身份证地址',
    key: 'identificationAddress',
    type: 'INPUT',
    errorMsg: ['请输入身份证地址'],
  },
];

export default vertifyCn;
